#!/usr/bin/env bash
# Health Sync on-device adapter - LOCAL TEST OVERLAY, fully automated.
#
# Materializes the gitignored overlay (healthsync-local.settings.gradle.kts,
# healthsync-local.app.gradle.kts, app/src/healthSyncLocal/) from the
# committed .example templates, so Health Sync builds against the real
# on-device adapter instead of the vendor-neutral no-op - with zero manual
# copy-pasting or hand-editing. Never touches any committed file; nothing
# this script writes can end up in git (see .gitignore).
#
# Run with -h/--help for usage.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

DEFAULT_COORDINATE="com.bwell:bwell-sdk-kotlin-healthsync-adapter-aggregator:1.20.0"

usage() {
  cat <<EOF
Usage: ./enable-local-adapter.sh [coordinate...]

Materializes the gitignored local-adapter overlay so Health Sync builds
against the real on-device adapter instead of the vendor-neutral no-op.
Safe to re-run - existing files are left alone except
healthsync-local.app.gradle.kts, which is regenerated every run to match
whatever coordinates you pass this time.

  coordinate   group:artifact:version, or artifact:version (com.bwell: is
               assumed if you omit the group id). Repeatable - pass several
               to add more than one adapter dependency.

Examples:
  ./enable-local-adapter.sh
    -> $DEFAULT_COORDINATE (default, no args)
  ./enable-local-adapter.sh bwell-sdk-kotlin-healthsync-adapter-aggregator:1.20.1
    -> com.bwell:bwell-sdk-kotlin-healthsync-adapter-aggregator:1.20.1
  ./enable-local-adapter.sh com.bwell:bwell-sdk-kotlin-healthsync-adapter-aggregator:1.20.0 com.other:extra-lib:2.0.0
    -> two implementation(...) lines, one per coordinate

After running, set credentials and build:
  export JFROG_READ_TOKEN=...   # required - a Bearer/reference token
  export JFROG_READ_USER=...    # optional - only if you were issued a username too
  ./gradlew :app:assembleDebug
EOF
}

for arg in "$@"; do
  if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
    usage
    exit 0
  fi
done

coordinates=()
if [[ $# -eq 0 ]]; then
  coordinates=("$DEFAULT_COORDINATE")
else
  for arg in "$@"; do
    colon_count=$(grep -o ":" <<< "$arg" | wc -l | tr -d ' ')
    case "$colon_count" in
      1) coordinates+=("com.bwell:$arg") ;;
      2) coordinates+=("$arg") ;;
      *)
        echo "error: invalid coordinate '$arg' - expected group:artifact:version or artifact:version" >&2
        echo >&2
        usage >&2
        exit 1
        ;;
    esac
  done
fi

echo "Adapter coordinate(s):"
for c in "${coordinates[@]}"; do echo "  - $c"; done
echo

# 1. Settings overlay - static, skip if it already exists (don't clobber
#    any credential-adjacent edits a developer may have made).
if [[ -f healthsync-local.settings.gradle.kts ]]; then
  echo "skip: healthsync-local.settings.gradle.kts already exists"
else
  cp healthsync-local.settings.gradle.kts.example healthsync-local.settings.gradle.kts
  echo "created: healthsync-local.settings.gradle.kts"
fi

# 2. App overlay - regenerated every run, since its content is a direct
#    function of the coordinates passed this time.
{
  echo "// GENERATED by enable-local-adapter.sh - re-run the script (with new"
  echo "// coordinates, if needed) rather than hand-editing this file; it will"
  echo "// be overwritten. See healthsync-local.app.gradle.kts.example for docs."
  echo
  echo "dependencies {"
  for c in "${coordinates[@]}"; do
    # Quoted-invoke, not implementation(...) - scripts applied via
    # apply(from=...) don't get AGP's precompiled type-safe accessors.
    echo "    \"implementation\"(\"$c\")"
  done
  echo "}"
} > healthsync-local.app.gradle.kts
echo "wrote: healthsync-local.app.gradle.kts (${#coordinates[@]} coordinate(s))"

# 3. Real bridge source - static, skip if it already exists.
bridge_dir="app/src/healthSyncLocal/java/com/bwell/sampleapp/healthsync"
bridge_file="$bridge_dir/HealthSyncAdapterBridge.kt"
mkdir -p "$bridge_dir"
if [[ -f "$bridge_file" ]]; then
  echo "skip: $bridge_file already exists"
else
  cp healthsync-local.HealthSyncAdapterBridge.kt.example "$bridge_file"
  echo "created: $bridge_file"
fi

# 4. Real manifest fragment - static, skip if it already exists.
manifest_file="app/src/healthSyncLocal/AndroidManifest.xml"
if [[ -f "$manifest_file" ]]; then
  echo "skip: $manifest_file already exists"
else
  cp healthsync-local.AndroidManifest.xml.example "$manifest_file"
  echo "created: $manifest_file"
fi

echo
echo "Done. Next steps:"
echo "  export JFROG_READ_TOKEN=...   # required - a Bearer/reference token"
echo "  export JFROG_READ_USER=...    # optional - only if you were issued a username too"
echo "  ./gradlew --stop && ./gradlew :app:assembleDebug"
