name: Android CI

on:
  workflow_dispatch:
  release:
      types: [created]  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: cd bwell-kotlin-android && chmod +x ./gradlew

    - name: Build Debug APK
      run: cd bwell-kotlin-android && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: bwell-kotlin-android/app/build/outputs/apk/debug/app-debug.apk
