name: APK Release

on:
  release:
      types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: cd bwell-kotlin-android && chmod +x ./gradlew

    - name: Build Debug APK
      run: cd bwell-kotlin-android && ./gradlew assembleDebug

    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.previoustag.outputs.tag }}
        files: bwell-kotlin-android/app/build/outputs/apk/debug/app-debug.apk
